export const configSiteStatic = {
  images: {
    logoHorizontal: "/assets/LogoHorizontal.webp",
    logoVertical: "/assets/LogoVertical.webp",
    coverBienestar: "/assets/img/cover-bienestar.webp",
    coverSalud: "/assets/img/cover-salud.webp",
    coverLifestyle: "/assets/img/cover-lifestyle.webp",
    coverConsejos: "/assets/img/cover-consejos.webp",
    coverFitness: "/assets/img/cover-fitness.webp",
    coverAmor: "/assets/img/cover-amor.webp",
    coverTest: "/assets/img/cover-tests.webp",
    coverVos: "/assets/img/cover-vos.webp",
    coverModa: "/assets/img/cover-moda.webp",
    coverBelleza: "/assets/img/cover-belleza.webp",
    coverRecetas: "/assets/img/cover-recetas.webp",
    coverCosmic: "/assets/img/cover-cosmic.webp"
  },
  icons: {
    iconoAtras: "/assets/icons/IconoAtras.png",
    iconoBuscar: "/assets/icons/IconoBuscar.webp",
    iconoBuscarBlack: "/assets/icons/IconoBuscarBlack.webp",
    iconoHome: "/assets/icons/IconoHome.webp",
    iconoFavorito: "/assets/icons/IconoFavorito.webp",
    iconoVideo2: "/assets/icons/IconoVideo2.webp",
    iconoBienestar: "/assets/icons/IconoBienestar.webp",
    iconoModa: "/assets/icons/IconoModa.webp",
    iconoBelleza: "/assets/icons/IconoBelleza.webp",
    iconoRecetas: "/assets/icons/IconoRecetas.webp",
    iconoAmor: "/assets/icons/IconoAmorySexo.webp",
    iconoTest: "/assets/icons/IconoTest.webp",
    iconoVos: "/assets/icons/IconoVos.webp",
    iconoCosmic: "/assets/icons/IconoCosmic.webp",
    iconoVideo: "/assets/icons/IconoVideo.png",
    iconoFavoritos: "/assets/icons/IconoFavoritos.webp",
    iconoSalud: "/assets/icons/IconoSalud.webp",
    iconoLifestyle: "/assets/icons/IconoLifestyle.webp",
    iconoConsejos: "/assets/icons/IconoConsejos.webp",
    iconoFitness: "/assets/icons/IconoFitness.webp",
    botonBienestar: "/assets/icons/BotonBienestar.webp",
    botonModa: "/assets/icons/BotonModa.webp",
    botonBelleza: "/assets/icons/BotonBelleza.webp",
    botonRecetas: "/assets/icons/BotonRecetas.webp",
    botonAmor: "/assets/icons/BotonAmorySexo.webp",
    botonCosmic: "/assets/icons/BotonCosmic.webp",
    botonVideos: "/assets/icons/BotonVideos.webp",
  },
};
